### PR TITLE
129/test and bug fix

### LINKED ISSUE #129: tests for new features

### PR DESCRIPTION
**Pull request by louisewang1**
close #129 
- fix the text-overflow on children cards
- tests for cc license
- tests for my lists

### CODE REVIEW

File: cypress/fixtures/items.js [hunk 1]
```diff
@@ -254,3 +255,5 @@ export const GRAASPER_ITEMS = [
     categories: [{ categoryId: SAMPLE_CATEGORIES[1].id }],
   },
 ];
+
+export const getNumberOfOwnPublishedItems = (memberId) => PUBLISHED_ITEMS.filter(({path, creator}) => path.split('.').length === 1 && creator === memberId).length
```
Comment (pyphilia) [inline cypress/fixtures/items.js:259]: `path.split('.').length===1` -> Wouldn't it be easier to test if it contains `.` ?

File: cypress/fixtures/members.js [hunk 2]
```diff
@@ -65,3 +65,6 @@ export const buildMemberWithFavorites = (favoriteItems) => ({
   ...CURRENT_USER,
   extra: { ...CURRENT_USER.extra, favoriteItems },
 });
+
+// directly use id instead import from item fixtures here to avoid loop in export
+export const FAVORITE_ITEMS = ['ecafbd2a-5688-11eb-ae93-0242ac130002', 'egafbd2a-5688-11eb-ae93-0242ac130002'];
```
Comment (pyphilia) [inline cypress/fixtures/members.js:70]: If you have a loop in export, it means you should define your variable elsewhere. Why not in items directly? Or in a new file.

File: cypress/integration/collection/ccLicense.spec.js [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+describe('CC License in Summary', () => {
+  buildPublicAndPrivateEnvironments().forEach((environment) => {
+    it(`Display item's cc license for ${environment.currentMember.name}`, () => {
+      cy.setUpApi(environment);
+
+      const item = PUBLISHED_ITEMS[0];
+      cy.visit(buildCollectionRoute(item.id));
+      cy.wait(COLLECTION_LOADING_TIME);
+
+      cy.get(`#${SUMMARY_CC_LICENSE_CONTAINER_ID}`).should('be.exist');
```
Comment (pyphilia) [inline cypress/integration/collection/ccLicense.spec.js:16]: Would it be possible to verify if the CC license is correct? (between the 2 possible options)

File: cypress/integration/myLists/myFavorites.spec.js [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+  MY_FAVORITES_COLLECTIONS_GRID,
+} from '../../support/selectors';
+import { ITEM_PUBLISHED_TAG } from '../../fixtures/itemTags';
+import { buildMemberWithFavorites, FAVORITE_ITEMS } from '../../fixtures/members';
+
+describe('My Favorite Items', () => {
+  describe('Current user', () => {
+    // check if title and headings are displayed correctly
+    it('display favorite items', () => {
+      cy.setUpApi({currentMember: buildMemberWithFavorites(FAVORITE_ITEMS), items: PUBLISHED_ITEMS});
```
Comment (pyphilia) [inline cypress/integration/myLists/myFavorites.spec.js:13]: Instead of creating by hand `FAVORITE_ITEMS`, why not pick them from `PUBLISHED_ITEMS` before `setUpApi`?

File: cypress/integration/myLists/myFavorites.spec.js [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+      cy.wait('@getCurrentMember');
+      cy.get(MY_FAVORITES_COLLECTIONS_GRID)
+      .children()
+      .should(
+        'have.length',
+        FAVORITE_ITEMS.length,
+      );
+    });
+  });
+});
```
Comment (pyphilia) [inline cypress/integration/myLists/myFavorites.spec.js:29]: Could we test that the application doesn't crash if there's a non-existent favorite item in the user's list?

File: cypress/integration/myLists/myLikes.spec.js [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+    it('display liked items', () => {
+      cy.setUpApi({currentMember: CURRENT_USER, items: PUBLISHED_ITEMS});
+      cy.visit(MY_LIST_ROUTE);
+
+      // click my likes tab
+      cy.get(`#${buildMyListNavigationTabId(MY_LIST_TABS.MY_LIKES)}`).click();
+
+      cy.wait('@getPublicItemsWithTags').then(({ request: { url } }) => {
+        expect(url).to.contain(ITEM_PUBLISHED_TAG.id);
+      });
```
Comment (pyphilia) [inline cypress/integration/myLists/myLikes.spec.js:24]: Why do you test the published tag for liked items?

File: cypress/integration/myLists/myFavorites.spec.js (hunk 5 above)
Comment (pyphilia) [reply cypress/integration/myLists/myFavorites.spec.js:29]: Could we also test that this tab/section is not available if you are logged out?

File: cypress/integration/myLists/myLikes.spec.js [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+      cy.wait('@getLikedItems');
+      cy.get(MY_LIKED_COLLECTIONS_GRID)
+      .children()
+      .should(
+        'have.length',
+        LIKED_ITEM_NUMBER,
+      );
+    });
+  });
+});
```
Comment (pyphilia) [inline cypress/integration/myLists/myLikes.spec.js:34]: Could we also test that this tab/section is not available if you are logged out?

File: cypress/integration/myLists/myPublishments.spec.js [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+import { MY_LIST_TABS } from '../../support/constants';
+
+describe('My Published Items', () => {
+  describe('Current user', () => {
+    // check if title and headings are displayed correctly
+    it('display published items', () => {
+      cy.setUpApi({currentMember: CURRENT_USER, items: PUBLISHED_ITEMS});
+      cy.visit(MY_LIST_ROUTE);
+
+      // click my likes tab
```
Comment (pyphilia) [inline cypress/integration/myLists/myPublishments.spec.js:18]: Remove?

File: cypress/support/constants.js [hunk 9]
```diff
@@ -22,3 +22,10 @@ export const THUMBNAIL_EXTENSION = 'image/jpeg';
 export const HOME_PAGE_LOADING_TIME = 3000;
 export const ALL_COLLECTIONS_LOADING_TIME = 3000;
 export const COLLECTION_LOADING_TIME = 3000;
+
+// my list tabs
+export const MY_LIST_TABS = {
```
Comment (pyphilia) [inline cypress/support/constants.js:27]: What does this do? If it's for selecting, you should apply "hardcoded" ids to the elements. Most probably you don't need a whole object just for testing.

File: src/config/selectors.js [hunk 10]
```diff
@@ -18,3 +18,6 @@ export const GRAASP_SELECTION_TITLE_ID = 'graaspSelectionTitleId';
 export const DISCOVER_SECTION_TITLE_ID = 'discoverSectionTitleId';
 
 export const buildMyListNavigationTabId = (index) => `nav-tab-${index}`;
+
+export const MY_FAVORITES_COLLECTIONS_ID = 'favoriteCollectionsGrid';
+export const MY_LIKES_COLLECTIONS_ID = 'likedCollectionsGrid';
```
Comment (pyphilia) [inline src/config/selectors.js:23]: It might be my mistake, but we shouldn't have multiple `selectors.js` file. Let's keep only the `src/config/selectors.js` one.

File: cypress/fixtures/itemLikes.js [hunk 11]
```diff
@@ -0,0 +1,15 @@
...
+    itemId: PUBLISHED_ITEMS[0].id,
+    memberId: MEMBERS.ANNA.id,
+  },
+  {
+    itemId: PUBLISHED_ITEMS[1].id,
+    memberId: MEMBERS.ANNA.id,
+  }
+]
+
+export const LIKED_ITEM_NUMBER = 1;
```
Comment (pyphilia) [inline cypress/fixtures/itemLikes.js:15]: Can't we dynamically compute this number? It's obviously related to the number of liked items you return.

**Review by pyphilia — CHANGES_REQUESTED** [review]
Thanks for the changes, I've left some comments 🐇

File: cypress/integration/myLists/myFavorites.spec.js (hunk 5 above)
Comment (louisewang1) [reply cypress/integration/myLists/myFavorites.spec.js:29]: > Could we also test that this tab/section is not available if you are logged out?

I see this one is already tested in the header, when user logged out, they won't see the entrance on header thus the whole page won't be visible

File: cypress/support/constants.js (hunk 9 above)
Comment (louisewang1) [reply cypress/support/constants.js:27]: It's the index of tabs. It's not for selecting directly, but to generate the element ids because the element id of the tab contains the index. Otherwise I'll pass in 0, 1, 2 but it's not so clear which represent which.

File: cypress/integration/collection/ccLicense.spec.js (hunk 3 above)
Comment (louisewang1) [reply cypress/integration/collection/ccLicense.spec.js:16]: The displayed element does not contain the value of the option, so it's hard to check that.

File: cypress/integration/myLists/myLikes.spec.js (hunk 6 above)
Comment (louisewang1) [reply cypress/integration/myLists/myLikes.spec.js:24]: The liked items also fetch the published items and then do a filtering

File: cypress/integration/myLists/myLikes.spec.js (hunk 7 above)
Comment (louisewang1) [reply cypress/integration/myLists/myLikes.spec.js:31]: Same as above

File: cypress/integration/myLists/myLikes.spec.js (hunk 6 above)
Comment (pyphilia) [reply cypress/integration/myLists/myLikes.spec.js:24]: Could you add this as a comment? We will probably have to change later the mechanism with a proper endpoint (GET /items/liked or similar).
