### PR TITLE
146/fix UI

### LINKED ISSUE #146: Bugs in new UI
Several bugs found in the new UI:
- the side menu is cut on top sometimes
- item card is cut

### PR DESCRIPTION
**Pull request by louisewang1**
close #146

### CODE REVIEW

File: src/components/collection/CollectionsGrid.js [hunk 1]
```diff
@@ -38,11 +44,19 @@ CollectionsGrid.propTypes = {
   id: PropTypes.string,
   collections: PropTypes.instanceOf(List),
   isLoading: PropTypes.bool.isRequired,
+  sm: PropTypes.instanceOf(Number),
```
Comment (pyphilia) [inline src/components/collection/CollectionsGrid.js:47]: Hum I think you can change it for `PropTypes.number`?

File: src/components/home/AllCollections.js [hunk 2]
```diff
@@ -57,7 +56,7 @@ const useStyles = makeStyles((theme) => ({
   },
   drawer: {
     width: LEFT_MENU_WIDTH,
-    flexShrink: 0,
+    // flexShrink: 0,
```
Comment (pyphilia) [inline src/components/home/AllCollections.js:59]: remove

File: src/config/constants.js [hunk 3]
```diff
@@ -44,7 +44,7 @@ export const TREE_VIEW_MIN_WIDTH = 350;
 export const TWITTER_MESSAGE_MAX_LENGTH = 270;
 export const MAIL_BREAK_LINE = '%0D%0A';
 
-export const LEFT_MENU_WIDTH = 300;
+export const LEFT_MENU_WIDTH = '18%';
```
Comment (pyphilia) [inline src/config/constants.js:47]: It's okay for me, but what happens on phone now? Did you set a min width? I know it won't be optimal in any case for phone, but it should at least be usable!

**Review by pyphilia — CHANGES_REQUESTED** [review]
Nice PR! I like how you deal with the Grid's column numbers. I have a concern about the menu on phones, otherwise I've left minor comments in this PR.
