### PR TITLE
fix: clicking on home should go to home

### LINKED ISSUE #38: clicking on logo should go back to home

### PR DESCRIPTION
**Pull request by hasanagh**
fixed clicking on home

fixes #38

### CODE REVIEW

**Review by juancarlosfarah — APPROVED** [review]

File: src/client/components/layout/Header.js [hunk 1]
```diff
@@ -27,10 +31,12 @@ function Header() {
     <header>
       <AppBar position="static">
         <Toolbar>
-          <Logo className={classes.logo} />
-          <Typography variant="h6" color="inherit" className={classes.grow}>
-            {t('Explore')}
-          </Typography>
+          <a href="/" className={classes.link}>
```
Comment (pyphilia) [inline src/client/components/layout/Header.js:34]: I don't know the convention, but maybe you can use `Link` from `react-router`.
And use  `HOME_ROUTE` for the link.

**Review by pyphilia — APPROVED** [review]
It was indeed necessary to go back to the home page from a collection! 👍

File: src/client/components/layout/Header.js (hunk 1 above)
Comment (hasanagh) [reply src/client/components/layout/Header.js:34]: I am not sure if the `Link` component works with static routing. When I tried it, I navigated to home but didn't get any collections (so I am not sure if it works with static routing and couldn't find information online)

Comment (pyphilia) [reply src/client/components/layout/Header.js:34]: @juancarlosfarah  @hasanagh Indeed I have the same result. In fact the routing happens, but since the data are not fetched when mounting `Home` there are no collection (collections are only fetched when rendering from the server). 
- I don't really know the conventions, should we check somehow if the render is done from the server or the client to fetch the data from the component? 
- Maybe we can decide by looking at `collections` in the context, fetch the collections if the value is `null` (while fetching no collection would return  `[]`)
- Or just using a `a` is okay.  

But in any case you can change `HOME_ROUTE` in your `a` tag^^ This does work.

Comment (hasanagh) [reply src/client/components/layout/Header.js:34]: Hey @pyphilia, I added `HOME_ROUTE`. As for the convention I am also not aware of it and checking how to deal with that.

Comment (hasanagh) [reply src/client/components/layout/Header.js]: @pyphilia  check [this](https://phrase.com/blog/posts/localized-server-side-rendering-with-react/#The_Navigation_Bar)

**Comment by pyphilia** [comment]
@hasanagh will you update this branch with the changes we mentioned last time? (how we fetch data) or will you use another PR? It's up to you whether you merge this branch now or after.

**Comment by hasanagh** [comment]
> @hasanagh will you update this branch with the changes we mentioned last time? (how we fetch data) or will you use another PR? It's up to you whether you merge this branch now or after.

I will merge this branch. and do the update on the other branch.
